name: Get Unity License

on:
  workflow_dispatch:

jobs:
  get-license:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.3.3f1-linux-il2cpp-3.1.0
    steps:
      - name: Activate Unity
        run: |
          unity-editor \
            -quit \
            -batchmode \
            -nographics \
            -username ${{ secrets.UNITY_EMAIL }} \
            -password ${{ secrets.UNITY_PASSWORD }} \
            -createManualActivationFile \
            -logfile /dev/stdout
      
      - name: Upload .alf file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_activation
          path: ./*.alf